### ISSUE TITLE
Error with     "SELLAMOUNTINTOKENS": "ALL",

### ISSUE THREAD

**Issue by tsarbuig2** [yaqub0r/LimitSwap#25]
I have this error 
```
ERROR: 2021-12-20 02:35:25,334 expected string or bytes-like object
Traceback (most recent call last):
  File "/Users/admin/Downloads/LimitSwap-last/LimitSwap.py", line 2580, in run
    tokens = load_tokens_file(command_line_args.tokens, True)
  File "/Users/admin/Downloads/LimitSwap-last/LimitSwap.py", line 569, in load_tokens_file
    elif re.search(r'^\d+$', token[key]):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
ERROR: 2021-12-20 02:35:25,336 expected string or bytes-like object
Traceback (most recent call last):
  File "/Users/admin/Downloads/LimitSwap-last/LimitSwap.py", line 2580, in run
    tokens = load_tokens_file(command_line_args.tokens, True)
  File "/Users/admin/Downloads/LimitSwap-last/LimitSwap.py", line 569, in load_tokens_file
    elif re.search(r'^\d+$', token[key]):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

with :

```
[
{

    "ENABLED": "true",

    "SYMBOL": "CAKE",
    "ADDRESS": "0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82", 
    "BUYAMOUNTINBASE": "0.000005",
    "BUYPRICEINBASE":  "0",
    "SELLPRICEINBASE": "550",
    "STOPLOSSPRICEINBASE": "0",

    "SLIPPAGE": "49",

    "MAXTOKENS": "0.0001",
    "MOONBAG": "0",

    "RUGDOC_CHECK": "true",
    "BUYAFTER_XXX_SECONDS": "20",    
    "MAX_FAILED_TRANSACTIONS_IN_A_ROW": "2",    
    
    "LIQUIDITYCHECK": "false",
    "LIQUIDITYAMOUNT": "1.5",
    "LIQUIDITYINNATIVETOKEN": "true",
    "USECUSTOMBASEPAIR": "false",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",

    "SELLAMOUNTINTOKENS": "0.0005",
    "HASFEES": "false",
    "GAS": "BOOST",
    "BOOSTPERCENT": "30",
    "GASLIMIT": "1000000",
    "GASPRIORITY_FOR_ETH_ONLY": "2.5"

  }
]
```

**Comment by tsarbuig2** [comment]
solved
