### ISSUE TITLE
error when not enough liquidity

### ISSUE THREAD

**Issue by tsarbuig** [yaqub0r/LimitSwap#9]
on ETH Rinkeby

```
[
  {

    "ENABLED": "true",

    "SYMBOL": "UNI",
    "ADDRESS": "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984", 
    "BUYAMOUNTINBASE": "0.0005",
    "BUYPRICEINBASE":  "10",
    "SELLPRICEINBASE": "0.5",
    "STOPLOSSPRICEINBASE": "0",

    "SLIPPAGE": "49",

    "MAXTOKENS": "20",
    "MOONBAG": "0",

    "RUGDOC_CHECK": "false",
    "BUYAFTER_XXX_SECONDS": "0",    
    "MAX_FAILED_TRANSACTIONS_IN_A_ROW": "2",    
    
    "LIQUIDITYCHECK": "false",
    "LIQUIDITYAMOUNT": "1.5",
    "LIQUIDITYINNATIVETOKEN": "true",
    "USECUSTOMBASEPAIR": "true",
    "BASESYMBOL": "WETH",
    "BASEADDRESS": "0xc778417e063141139fce010982780140aa0cd5ab",

    "SELLAMOUNTINTOKENS": "0.0005",
    "HASFEES": "false",
    "GAS": "6",
    "BOOSTPERCENT": "30",
    "GASLIMIT": "1000000",
    "GASPRIORITY_FOR_ETH_ONLY": "2.5"

  }
]

```
```
ERROR: 2021-12-17 09:58:05,710 execution reverted: UniswapV2Library: INSUFFICIENT_LIQUIDITY
Traceback (most recent call last):
  File "/Users/ceciliavaury/Downloads/LimitSwap-last/LimitSwapyak.py", line 2369, in run
    quote = check_price(inToken, outToken, token['SYMBOL'], token['BASESYMBOL'],
  File "/Users/ceciliavaury/Downloads/LimitSwap-last/LimitSwapyak.py", line 1288, in check_price
    price_check = routerContract.functions.getAmountsOut(1 * DECIMALS, [inToken, weth, outToken]).call()[-1]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/contract.py", line 959, in call
    return call_contract_function(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/contract.py", line 1503, in call_contract_function
    return_data = web3.eth.call(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/manager.py", line 167, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/manager.py", line 67, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/_utils/method_formatters.py", line 569, in raise_solidity_error_on_revert

```

**Comment by yaqub0r** [comment]
I couldn't mimic this error. Please paste the console information. This is what I got:

2021-12-18 06:39:22.588008 reserves[0] is for outToken:
2021-12-18 06:39:22.588188 Debug reserves[0] : 97432.17334224342
2021-12-18 06:39:22.588278 Debug reserves[1] : 336765496.0313144
2021-12-18 06:39:22.588351 Debug LIQUIDITYAMOUNT : 97432.17334224342 in token: 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
2021-12-18 06:39:22.588432 Found liquidity for HERO
2021-12-18 06:39:22.618874 reserves[0] is for outToken:
2021-12-18 06:39:22.619000 Debug reserves[0] : 97432.17334224342
2021-12-18 06:39:22.619086 Debug reserves[1] : 336765496.0313144
2021-12-18 06:39:22.619158 Debug LIQUIDITYAMOUNT : 97432.17334224342 in token: 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
2021-12-18 06:39:22.619241 You have set LIQUIDITYCHECK = true.
2021-12-18 06:39:22.619308 Current HERO Liquidity = 97432 in token: 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
2021-12-18 06:39:22.619399 LIQUIDITYAMOUNT parameter = 100000000000  : not enough liquidity, bot will not buy. Disableing the trade of this token.

**Comment by yaqub0r** [comment]
I'm not sure how you got this error. Please check it again on the latest version.

**Comment by tsarbuig2** [comment]
use this settings.json : 

    "USECUSTOMNODE": "true",
    "CUSTOMNODE": "https://rinkeby-light.eth.linkpool.io",
    "EXCHANGE": "uniswap",
    "EXCHANGEVERSION": "2",


and the tokens.json above
